### PR TITLE
#6 Remove composer installer, to not copy app/code

### PR DESCRIPTION
**Pull request by amenk**
Module should not be copied to app/code
See also the core modules

### CODE REVIEW

**Comment by paales** [comment]
@amenk Thought that didn't happen anymore, changed something for that here https://github.com/ho-nl/magento2-Ho_Templatehints/commit/8ba55756e40559cbdd5a48bba3a6e5ed3bc40747

**Comment by amenk** [comment]
Turns out that I was using an old (tagged) version - not dev-master

**Comment by paales** [comment]
Do you know if the above change is required, or does this break the autoloader/installer?

**Comment by amenk** [comment]
I don't think anymore it is required - but it should not break anything, as the core modules use similar composer.json files.

**Pull request merged**
